### ISSUE TITLE
I need some help 

### ISSUE THREAD

**Issue by I-DRS-I** [prawigya/shiny-bot-pokemon#1]
Hi, 

I need some help, or a kind of tutorial to use this tool.
For exemple a step by step ( what kind of emulator use ) 
and maybe and exemple of working save/emulator combo.

Thank you very much ;) 

R.

**Comment by noodle42069** [comment]
Just run the program and every error look that up on the web install and procede

**Comment by MarbleQ22** [comment]
> Just run the program and every error look that up on the web install and procede

This is beyond not helpful. Please be more descriptive. How would I run this?

**Comment by prawigya** [comment]
Hi, @I-DRS-I  @MarbleQ22  I have addressed the problem in [this issue](https://github.com/prawigya/shiny-bot-pokemon/issues/3). Can you have a look at it, and also at the instructions described in the Readme to make modifications according to your system and try running the script?
