### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by LinkTheLinker** [prawigya/shiny-bot-pokemon#2]
Hello, I've been trying to run the bot, but it seems to not be working, the screenshooter and keyboard scripts work, but the functions script immediately closes. Is it because I need a separate controller connected to my computer so that it does the inputs? Thank you.

**Comment by MarbleQ22** [comment]
How were you able to run the scripts? Im having trouble with that. Did you have to set anything up beforehand?

**Comment by prawigya** [comment]
Hi, @LinkTheLinker  I have addressed the problem in [this issue](https://github.com/prawigya/shiny-bot-pokemon/issues/3). Can you have a look at it, and also the instructions described in the Readme to make modifications according to your system and try running the script? 

Also you do not need a separate controller connected to your computer, your keyboard will do just fine.
